array = ['Red', 'Green', 'White', 'Black'];
console.log(array);
let arrLength = array.push('Yellow ', 'Blue');
console.log(arrLength);
console.log(array);
let removedElement = array.pop();
console.log(removedElement);
console.log(array);
removedElements = array[3] = 'Orange';
console.log(removedElement);
console.log(array);
removedElements = array.shift();
console.log(removedElement);
console.log(array);
arrLength = array.unshift('Fuchsia', 'Purple');
console.log(arrLength);
console.log(array);
let copy = array.slice(2);
console.log(copy);
console.log(array);
